name: 버그 제보
description: 의도대로 동작하지 않는 기능
title: "[BUG] "
labels: [bug]
body:
  - type: dropdown
    id: area
    attributes:
      label: 영역
      options:
        - server
        - client
        - common
        - ci
    validations:
      required: true

  - type: textarea
    id: situation
    attributes:
      label: 문제 상황
      description: 무엇이 어떻게 잘못 동작하나요.
    validations:
      required: true
