name: 문서 작업
description: 문서 추가 또는 수정
title: "[DOCS] "
labels: [documentation]
body:
  - type: dropdown
    id: area
    attributes:
      label: 영역
      options:
        - server
        - client
        - common
        - ci
    validations:
      required: true

  - type: textarea
    id: target
    attributes:
      label: 대상
      description: 어떤 문서를 다루나요.
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: 작업 내용
      value: |
        -
    validations:
      required: true
