name: 기능 추가
description: 새로 구현할 기능
title: "[FEAT] "
labels: [feat]
body:
  - type: dropdown
    id: area
    attributes:
      label: 영역
      options:
        - server
        - client
        - common
        - ci
    validations:
      required: true

  - type: textarea
    id: work
    attributes:
      label: 작업 내용
      value: |
        -
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: 체크리스트
      value: |
        - [ ]
    validations:
      required: false
