name: 리팩토링
description: 동작 변경 없는 코드 개선
title: "[REFACTOR] "
labels: [refactor]
body:
  - type: dropdown
    id: area
    attributes:
      label: 영역
      options:
        - server
        - client
        - common
        - ci
    validations:
      required: true

  - type: textarea
    id: target
    attributes:
      label: 대상
      description: 어떤 코드를 개선하나요.
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: 개선 내용
      value: |
        -
    validations:
      required: true
